language: objective-c
osx_image: xcode8
script:
    - make test
    - make lint
matrix:
    include:
        - env: SCHEME=SentryCrash WORKSPACE=Mac.xcworkspace SDK=macosx10.12
        - env: SCHEME=SentryCrashLib WORKSPACE=iOS.xcworkspace SDK=iphonesimulator
        - env: SCHEME=SentryCrash-TVOS WORKSPACE=TVOS.xcworkspace SDK=appletvsimulator
